### ISSUE TITLE
Add more supported models

### ISSUE THREAD

**Issue by yichuan1998** [developer0hye/onepose#1]
This is a great repo! Thanks for your job. How can I Add else Vitpose model? I tried modifying model_config but failed, and got the error:
 >
![image](https://github.com/developer0hye/onepose/assets/91551667/d543c728-a68c-4800-b61c-2dad133511e4)
![image](https://github.com/developer0hye/onepose/assets/91551667/063d6648-ccce-45c0-9fe0-66f2fbbb2cb9)
Thanks

**Comment by developer0hye** [comment]
@yichuan1998 Hi!

Which model do you want to add? 
Honestly, this code is not optimal for adding other models now. Let me know the model what you want to add.

**Comment by yichuan1998** [comment]
Now ViTPose_small_simple_coco_256x192 is what I need. Also I want to learn how to add it in local environment. 
![image](https://github.com/developer0hye/onepose/assets/91551667/e825dc4b-68f8-4d05-b871-5b1513caf70d)

**Comment by developer0hye** [comment]
@yichuan1998 Do you have weights file?

**Comment by yichuan1998** [comment]
I downloaded it from there
![image](https://github.com/developer0hye/onepose/assets/91551667/7f9616a3-35df-40c5-a6ad-517025f07fbe)

**Comment by developer0hye** [comment]
@yichuan1998 I tried to add vitpose-s for you, but I failed to load pretrained weights with this error.

![image](https://github.com/developer0hye/onepose/assets/35001605/e9386968-de2c-4d2e-aaee-7068be9ad984)

**Comment by yichuan1998** [comment]
> @yichuan1998我尝试为您添加 vitpose-s，但由于此错误，我无法加载预训练权重。
> 
> ![图像](https://user-images.githubusercontent.com/35001605/280440388-e9386968-de2c-4d2e-aaee-7068be9ad984.png)

That's weird. Thanks for your work.
