### ISSUE TITLE
how to plot the skeleton having the top of head?

### ISSUE THREAD

**Issue by leolle520** [developer0hye/onepose#3]
I see you having a visualization of the skeleton going from the top to the neck, how to have this?
Thank you.

**Comment by developer0hye** [comment]
Hello, @leolle520 

Try to run the below code.

```python
import cv2
import onepose
img = cv2.imread("sample.png")
keypoints = onepose.create_model('ViTPose_huge_mpii').to("cuda")(img)
onepose.visualize_keypoints(img, keypoints, model.keypoint_info, model.skeleton_info)
cv2.imshow('img', img)
cv2.waitKey(0)
```

**Comment by leolle520** [comment]
Hi Kwon,
Thank you for you replying.
I mean like the middle skeleton of image:
https://github.com/developer0hye/onepose/blob/main/onepose/assets/sample_all_vis.png
,
The method above gives the left skeleton.


Yonghye Kwon ***@***.***> 于2024年6月13日周四 21:30写道：

**Comment by developer0hye** [comment]
@leolle520 

There is an error in code. Try this code

```python
import cv2
import onepose
from google.colab.patches import cv2_imshow

if __name__ == '__main__':
    img = cv2.imread('sample.png')
    model = onepose.create_model('ViTPose_huge_mpii')

    keypoints = model(img)
    onepose.visualize_keypoints(img, keypoints, model.keypoint_info, model.skeleton_info)
    cv2.imshow('img', img)
    cv2.waitKey(0)
```

https://colab.research.google.com/drive/17nmWymCYlFQM59qAoyF03YbSUZC_0g1S?usp=sharing

![image](https://github.com/developer0hye/onepose/assets/35001605/ea8d35c6-cd44-4dc2-86e6-6cf9d1b9d0cc)

**Comment by leolle520** [comment]
Thank you Kwon.
The specific ViTPose_huge_mpii solve my problem.
I have another question: Is it able to do the human instance segmentation with the ViTPose model?

**Comment by developer0hye** [comment]
@leolle520 
It's hard to use it as an instance segmentation model but if you use both it and segment anything of meta, you may get results that you want.
